//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.237
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoClassing.VServerServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VServerServices.WebServicesSoap")]
    public interface WebServicesSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetDocResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDoc", ReplyAction="*")]
        GoClassing.VServerServices.GetDocResponse GetDoc(GoClassing.VServerServices.GetDocRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 filename 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDoc", ReplyAction="*")]
        GoClassing.VServerServices.DelDocResponse DelDoc(GoClassing.VServerServices.DelDocRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 receiver 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMail", ReplyAction="*")]
        GoClassing.VServerServices.SendMailResponse SendMail(GoClassing.VServerServices.SendMailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDoc", Namespace="http://tempuri.org/", Order=0)]
        public GoClassing.VServerServices.GetDocRequestBody Body;
        
        public GetDocRequest() {
        }
        
        public GetDocRequest(GoClassing.VServerServices.GetDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDocRequestBody {
        
        public GetDocRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoClassing.VServerServices.GetDocResponseBody Body;
        
        public GetDocResponse() {
        }
        
        public GetDocResponse(GoClassing.VServerServices.GetDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDocResult;
        
        public GetDocResponseBody() {
        }
        
        public GetDocResponseBody(string GetDocResult) {
            this.GetDocResult = GetDocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDoc", Namespace="http://tempuri.org/", Order=0)]
        public GoClassing.VServerServices.DelDocRequestBody Body;
        
        public DelDocRequest() {
        }
        
        public DelDocRequest(GoClassing.VServerServices.DelDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelDocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public DelDocRequestBody() {
        }
        
        public DelDocRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoClassing.VServerServices.DelDocResponseBody Body;
        
        public DelDocResponse() {
        }
        
        public DelDocResponse(GoClassing.VServerServices.DelDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DelDocResponseBody {
        
        public DelDocResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMail", Namespace="http://tempuri.org/", Order=0)]
        public GoClassing.VServerServices.SendMailRequestBody Body;
        
        public SendMailRequest() {
        }
        
        public SendMailRequest(GoClassing.VServerServices.SendMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string receiver;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string body;
        
        public SendMailRequestBody() {
        }
        
        public SendMailRequestBody(string receiver, string title, string body) {
            this.receiver = receiver;
            this.title = title;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public GoClassing.VServerServices.SendMailResponseBody Body;
        
        public SendMailResponse() {
        }
        
        public SendMailResponse(GoClassing.VServerServices.SendMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendMailResponseBody {
        
        public SendMailResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicesSoapChannel : GoClassing.VServerServices.WebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicesSoapClient : System.ServiceModel.ClientBase<GoClassing.VServerServices.WebServicesSoap>, GoClassing.VServerServices.WebServicesSoap {
        
        public WebServicesSoapClient() {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoClassing.VServerServices.GetDocResponse GoClassing.VServerServices.WebServicesSoap.GetDoc(GoClassing.VServerServices.GetDocRequest request) {
            return base.Channel.GetDoc(request);
        }
        
        public string GetDoc() {
            GoClassing.VServerServices.GetDocRequest inValue = new GoClassing.VServerServices.GetDocRequest();
            inValue.Body = new GoClassing.VServerServices.GetDocRequestBody();
            GoClassing.VServerServices.GetDocResponse retVal = ((GoClassing.VServerServices.WebServicesSoap)(this)).GetDoc(inValue);
            return retVal.Body.GetDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoClassing.VServerServices.DelDocResponse GoClassing.VServerServices.WebServicesSoap.DelDoc(GoClassing.VServerServices.DelDocRequest request) {
            return base.Channel.DelDoc(request);
        }
        
        public void DelDoc(string filename) {
            GoClassing.VServerServices.DelDocRequest inValue = new GoClassing.VServerServices.DelDocRequest();
            inValue.Body = new GoClassing.VServerServices.DelDocRequestBody();
            inValue.Body.filename = filename;
            GoClassing.VServerServices.DelDocResponse retVal = ((GoClassing.VServerServices.WebServicesSoap)(this)).DelDoc(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoClassing.VServerServices.SendMailResponse GoClassing.VServerServices.WebServicesSoap.SendMail(GoClassing.VServerServices.SendMailRequest request) {
            return base.Channel.SendMail(request);
        }
        
        public void SendMail(string receiver, string title, string body) {
            GoClassing.VServerServices.SendMailRequest inValue = new GoClassing.VServerServices.SendMailRequest();
            inValue.Body = new GoClassing.VServerServices.SendMailRequestBody();
            inValue.Body.receiver = receiver;
            inValue.Body.title = title;
            inValue.Body.body = body;
            GoClassing.VServerServices.SendMailResponse retVal = ((GoClassing.VServerServices.WebServicesSoap)(this)).SendMail(inValue);
        }
    }
}
