//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoClassing.MFLMirrorServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MirrorServices.MFL/", ConfigurationName="MFLMirrorServices.WebServicesSoap")]
    public interface WebServicesSoap {
        
        // CODEGEN: 命名空间 http://MirrorServices.MFL/ 的元素名称 dayHash 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://MirrorServices.MFL/TryAccessCache", ReplyAction="*")]
        GoClassing.MFLMirrorServices.TryAccessCacheResponse TryAccessCache(GoClassing.MFLMirrorServices.TryAccessCacheRequest request);
        
        // CODEGEN: 命名空间 http://MirrorServices.MFL/ 的元素名称 dayHash 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://MirrorServices.MFL/Expires", ReplyAction="*")]
        GoClassing.MFLMirrorServices.ExpiresResponse Expires(GoClassing.MFLMirrorServices.ExpiresRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TryAccessCacheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TryAccessCache", Namespace="http://MirrorServices.MFL/", Order=0)]
        public GoClassing.MFLMirrorServices.TryAccessCacheRequestBody Body;
        
        public TryAccessCacheRequest() {
        }
        
        public TryAccessCacheRequest(GoClassing.MFLMirrorServices.TryAccessCacheRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MirrorServices.MFL/")]
    public partial class TryAccessCacheRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dayHash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string path;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool secret;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string validation;
        
        public TryAccessCacheRequestBody() {
        }
        
        public TryAccessCacheRequestBody(string dayHash, string path, string url, bool secret, string validation) {
            this.dayHash = dayHash;
            this.path = path;
            this.url = url;
            this.secret = secret;
            this.validation = validation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TryAccessCacheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TryAccessCacheResponse", Namespace="http://MirrorServices.MFL/", Order=0)]
        public GoClassing.MFLMirrorServices.TryAccessCacheResponseBody Body;
        
        public TryAccessCacheResponse() {
        }
        
        public TryAccessCacheResponse(GoClassing.MFLMirrorServices.TryAccessCacheResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MirrorServices.MFL/")]
    public partial class TryAccessCacheResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool TryAccessCacheResult;
        
        public TryAccessCacheResponseBody() {
        }
        
        public TryAccessCacheResponseBody(bool TryAccessCacheResult) {
            this.TryAccessCacheResult = TryAccessCacheResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExpiresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Expires", Namespace="http://MirrorServices.MFL/", Order=0)]
        public GoClassing.MFLMirrorServices.ExpiresRequestBody Body;
        
        public ExpiresRequest() {
        }
        
        public ExpiresRequest(GoClassing.MFLMirrorServices.ExpiresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://MirrorServices.MFL/")]
    public partial class ExpiresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dayHash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string path;
        
        public ExpiresRequestBody() {
        }
        
        public ExpiresRequestBody(string dayHash, string path) {
            this.dayHash = dayHash;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExpiresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExpiresResponse", Namespace="http://MirrorServices.MFL/", Order=0)]
        public GoClassing.MFLMirrorServices.ExpiresResponseBody Body;
        
        public ExpiresResponse() {
        }
        
        public ExpiresResponse(GoClassing.MFLMirrorServices.ExpiresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExpiresResponseBody {
        
        public ExpiresResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicesSoapChannel : GoClassing.MFLMirrorServices.WebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicesSoapClient : System.ServiceModel.ClientBase<GoClassing.MFLMirrorServices.WebServicesSoap>, GoClassing.MFLMirrorServices.WebServicesSoap {
        
        public WebServicesSoapClient() {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoClassing.MFLMirrorServices.TryAccessCacheResponse GoClassing.MFLMirrorServices.WebServicesSoap.TryAccessCache(GoClassing.MFLMirrorServices.TryAccessCacheRequest request) {
            return base.Channel.TryAccessCache(request);
        }
        
        public bool TryAccessCache(string dayHash, string path, string url, bool secret, string validation) {
            GoClassing.MFLMirrorServices.TryAccessCacheRequest inValue = new GoClassing.MFLMirrorServices.TryAccessCacheRequest();
            inValue.Body = new GoClassing.MFLMirrorServices.TryAccessCacheRequestBody();
            inValue.Body.dayHash = dayHash;
            inValue.Body.path = path;
            inValue.Body.url = url;
            inValue.Body.secret = secret;
            inValue.Body.validation = validation;
            GoClassing.MFLMirrorServices.TryAccessCacheResponse retVal = ((GoClassing.MFLMirrorServices.WebServicesSoap)(this)).TryAccessCache(inValue);
            return retVal.Body.TryAccessCacheResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GoClassing.MFLMirrorServices.ExpiresResponse GoClassing.MFLMirrorServices.WebServicesSoap.Expires(GoClassing.MFLMirrorServices.ExpiresRequest request) {
            return base.Channel.Expires(request);
        }
        
        public void Expires(string dayHash, string path) {
            GoClassing.MFLMirrorServices.ExpiresRequest inValue = new GoClassing.MFLMirrorServices.ExpiresRequest();
            inValue.Body = new GoClassing.MFLMirrorServices.ExpiresRequestBody();
            inValue.Body.dayHash = dayHash;
            inValue.Body.path = path;
            GoClassing.MFLMirrorServices.ExpiresResponse retVal = ((GoClassing.MFLMirrorServices.WebServicesSoap)(this)).Expires(inValue);
        }
    }
}
