//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFamilyLodge.AdminService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hash 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeactiveLodge", ReplyAction="*")]
        MyFamilyLodge.AdminService.DeactiveLodgeResponse DeactiveLodge(MyFamilyLodge.AdminService.DeactiveLodgeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 hash 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActiveLodge", ReplyAction="*")]
        MyFamilyLodge.AdminService.ActiveLodgeResponse ActiveLodge(MyFamilyLodge.AdminService.ActiveLodgeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeactiveLodgeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeactiveLodge", Namespace="http://tempuri.org/", Order=0)]
        public MyFamilyLodge.AdminService.DeactiveLodgeRequestBody Body;
        
        public DeactiveLodgeRequest() {
        }
        
        public DeactiveLodgeRequest(MyFamilyLodge.AdminService.DeactiveLodgeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeactiveLodgeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lodgeName;
        
        public DeactiveLodgeRequestBody() {
        }
        
        public DeactiveLodgeRequestBody(string hash, string lodgeName) {
            this.hash = hash;
            this.lodgeName = lodgeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeactiveLodgeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeactiveLodgeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyFamilyLodge.AdminService.DeactiveLodgeResponseBody Body;
        
        public DeactiveLodgeResponse() {
        }
        
        public DeactiveLodgeResponse(MyFamilyLodge.AdminService.DeactiveLodgeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeactiveLodgeResponseBody {
        
        public DeactiveLodgeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActiveLodgeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActiveLodge", Namespace="http://tempuri.org/", Order=0)]
        public MyFamilyLodge.AdminService.ActiveLodgeRequestBody Body;
        
        public ActiveLodgeRequest() {
        }
        
        public ActiveLodgeRequest(MyFamilyLodge.AdminService.ActiveLodgeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActiveLodgeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lodgeName;
        
        public ActiveLodgeRequestBody() {
        }
        
        public ActiveLodgeRequestBody(string hash, string lodgeName) {
            this.hash = hash;
            this.lodgeName = lodgeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActiveLodgeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActiveLodgeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyFamilyLodge.AdminService.ActiveLodgeResponseBody Body;
        
        public ActiveLodgeResponse() {
        }
        
        public ActiveLodgeResponse(MyFamilyLodge.AdminService.ActiveLodgeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActiveLodgeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActiveLodgeResult;
        
        public ActiveLodgeResponseBody() {
        }
        
        public ActiveLodgeResponseBody(bool ActiveLodgeResult) {
            this.ActiveLodgeResult = ActiveLodgeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : MyFamilyLodge.AdminService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<MyFamilyLodge.AdminService.WebServiceSoap>, MyFamilyLodge.AdminService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFamilyLodge.AdminService.DeactiveLodgeResponse MyFamilyLodge.AdminService.WebServiceSoap.DeactiveLodge(MyFamilyLodge.AdminService.DeactiveLodgeRequest request) {
            return base.Channel.DeactiveLodge(request);
        }
        
        public void DeactiveLodge(string hash, string lodgeName) {
            MyFamilyLodge.AdminService.DeactiveLodgeRequest inValue = new MyFamilyLodge.AdminService.DeactiveLodgeRequest();
            inValue.Body = new MyFamilyLodge.AdminService.DeactiveLodgeRequestBody();
            inValue.Body.hash = hash;
            inValue.Body.lodgeName = lodgeName;
            MyFamilyLodge.AdminService.DeactiveLodgeResponse retVal = ((MyFamilyLodge.AdminService.WebServiceSoap)(this)).DeactiveLodge(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFamilyLodge.AdminService.ActiveLodgeResponse MyFamilyLodge.AdminService.WebServiceSoap.ActiveLodge(MyFamilyLodge.AdminService.ActiveLodgeRequest request) {
            return base.Channel.ActiveLodge(request);
        }
        
        public bool ActiveLodge(string hash, string lodgeName) {
            MyFamilyLodge.AdminService.ActiveLodgeRequest inValue = new MyFamilyLodge.AdminService.ActiveLodgeRequest();
            inValue.Body = new MyFamilyLodge.AdminService.ActiveLodgeRequestBody();
            inValue.Body.hash = hash;
            inValue.Body.lodgeName = lodgeName;
            MyFamilyLodge.AdminService.ActiveLodgeResponse retVal = ((MyFamilyLodge.AdminService.WebServiceSoap)(this)).ActiveLodge(inValue);
            return retVal.Body.ActiveLodgeResult;
        }
    }
}
