//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MFLMirror
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class MMEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“MMEntities”部分中的连接字符串初始化新 MMEntities 对象。
        /// </summary>
        public MMEntities() : base("name=MMEntities", "MMEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MMEntities 对象。
        /// </summary>
        public MMEntities(string connectionString) : base(connectionString, "MMEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MMEntities 对象。
        /// </summary>
        public MMEntities(EntityConnection connection) : base(connection, "MMEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MM_secret> MM_secret
        {
            get
            {
                if ((_MM_secret == null))
                {
                    _MM_secret = base.CreateObjectSet<MM_secret>("MM_secret");
                }
                return _MM_secret;
            }
        }
        private ObjectSet<MM_secret> _MM_secret;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<XLVExp_lodge> XLVExp_lodge
        {
            get
            {
                if ((_XLVExp_lodge == null))
                {
                    _XLVExp_lodge = base.CreateObjectSet<XLVExp_lodge>("XLVExp_lodge");
                }
                return _XLVExp_lodge;
            }
        }
        private ObjectSet<XLVExp_lodge> _XLVExp_lodge;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 MM_secret EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMM_secret(MM_secret mM_secret)
        {
            base.AddObject("MM_secret", mM_secret);
        }
    
        /// <summary>
        /// 用于向 XLVExp_lodge EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToXLVExp_lodge(XLVExp_lodge xLVExp_lodge)
        {
            base.AddObject("XLVExp_lodge", xLVExp_lodge);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MFLMirror", Name="MM_secret")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MM_secret : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MM_secret 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="path">path 属性的初始值。</param>
        /// <param name="validation">validation 属性的初始值。</param>
        public static MM_secret CreateMM_secret(global::System.Int32 id, global::System.String path, global::System.String validation)
        {
            MM_secret mM_secret = new MM_secret();
            mM_secret.id = id;
            mM_secret.path = path;
            mM_secret.validation = validation;
            return mM_secret;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String path
        {
            get
            {
                return _path;
            }
            set
            {
                OnpathChanging(value);
                ReportPropertyChanging("path");
                _path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("path");
                OnpathChanged();
            }
        }
        private global::System.String _path;
        partial void OnpathChanging(global::System.String value);
        partial void OnpathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String validation
        {
            get
            {
                return _validation;
            }
            set
            {
                OnvalidationChanging(value);
                ReportPropertyChanging("validation");
                _validation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("validation");
                OnvalidationChanged();
            }
        }
        private global::System.String _validation;
        partial void OnvalidationChanging(global::System.String value);
        partial void OnvalidationChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MFLMirror", Name="XLVExp_lodge")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class XLVExp_lodge : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 XLVExp_lodge 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="tracker">tracker 属性的初始值。</param>
        /// <param name="trackerArg">trackerArg 属性的初始值。</param>
        /// <param name="province">province 属性的初始值。</param>
        /// <param name="city">city 属性的初始值。</param>
        /// <param name="title">title 属性的初始值。</param>
        /// <param name="url">url 属性的初始值。</param>
        /// <param name="imgurl">imgurl 属性的初始值。</param>
        /// <param name="prize">prize 属性的初始值。</param>
        /// <param name="extradata">extradata 属性的初始值。</param>
        /// <param name="tel">tel 属性的初始值。</param>
        public static XLVExp_lodge CreateXLVExp_lodge(global::System.Int32 id, global::System.String tracker, global::System.String trackerArg, global::System.String province, global::System.String city, global::System.String title, global::System.String url, global::System.String imgurl, global::System.String prize, global::System.String extradata, global::System.String tel)
        {
            XLVExp_lodge xLVExp_lodge = new XLVExp_lodge();
            xLVExp_lodge.id = id;
            xLVExp_lodge.tracker = tracker;
            xLVExp_lodge.trackerArg = trackerArg;
            xLVExp_lodge.province = province;
            xLVExp_lodge.city = city;
            xLVExp_lodge.title = title;
            xLVExp_lodge.url = url;
            xLVExp_lodge.imgurl = imgurl;
            xLVExp_lodge.prize = prize;
            xLVExp_lodge.extradata = extradata;
            xLVExp_lodge.tel = tel;
            return xLVExp_lodge;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tracker
        {
            get
            {
                return _tracker;
            }
            set
            {
                OntrackerChanging(value);
                ReportPropertyChanging("tracker");
                _tracker = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tracker");
                OntrackerChanged();
            }
        }
        private global::System.String _tracker;
        partial void OntrackerChanging(global::System.String value);
        partial void OntrackerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String trackerArg
        {
            get
            {
                return _trackerArg;
            }
            set
            {
                OntrackerArgChanging(value);
                ReportPropertyChanging("trackerArg");
                _trackerArg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("trackerArg");
                OntrackerArgChanged();
            }
        }
        private global::System.String _trackerArg;
        partial void OntrackerArgChanging(global::System.String value);
        partial void OntrackerArgChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String province
        {
            get
            {
                return _province;
            }
            set
            {
                OnprovinceChanging(value);
                ReportPropertyChanging("province");
                _province = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("province");
                OnprovinceChanged();
            }
        }
        private global::System.String _province;
        partial void OnprovinceChanging(global::System.String value);
        partial void OnprovinceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String imgurl
        {
            get
            {
                return _imgurl;
            }
            set
            {
                OnimgurlChanging(value);
                ReportPropertyChanging("imgurl");
                _imgurl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("imgurl");
                OnimgurlChanged();
            }
        }
        private global::System.String _imgurl;
        partial void OnimgurlChanging(global::System.String value);
        partial void OnimgurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prize
        {
            get
            {
                return _prize;
            }
            set
            {
                OnprizeChanging(value);
                ReportPropertyChanging("prize");
                _prize = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prize");
                OnprizeChanged();
            }
        }
        private global::System.String _prize;
        partial void OnprizeChanging(global::System.String value);
        partial void OnprizeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String extradata
        {
            get
            {
                return _extradata;
            }
            set
            {
                OnextradataChanging(value);
                ReportPropertyChanging("extradata");
                _extradata = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("extradata");
                OnextradataChanged();
            }
        }
        private global::System.String _extradata;
        partial void OnextradataChanging(global::System.String value);
        partial void OnextradataChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tel
        {
            get
            {
                return _tel;
            }
            set
            {
                OntelChanging(value);
                ReportPropertyChanging("tel");
                _tel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tel");
                OntelChanged();
            }
        }
        private global::System.String _tel;
        partial void OntelChanging(global::System.String value);
        partial void OntelChanged();

        #endregion
    
    }

    #endregion
    
}
