//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileLocker.DevService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DevService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 filePath 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LockFile", ReplyAction="*")]
        FileLocker.DevService.LockFileResponse LockFile(FileLocker.DevService.LockFileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 filePath 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnlockFile", ReplyAction="*")]
        FileLocker.DevService.UnlockFileResponse UnlockFile(FileLocker.DevService.UnlockFileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetLockedFileResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLockedFile", ReplyAction="*")]
        FileLocker.DevService.GetLockedFileResponse GetLockedFile(FileLocker.DevService.GetLockedFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LockFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LockFile", Namespace="http://tempuri.org/", Order=0)]
        public FileLocker.DevService.LockFileRequestBody Body;
        
        public LockFileRequest() {
        }
        
        public LockFileRequest(FileLocker.DevService.LockFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LockFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        public LockFileRequestBody() {
        }
        
        public LockFileRequestBody(string filePath, string userName) {
            this.filePath = filePath;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LockFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LockFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileLocker.DevService.LockFileResponseBody Body;
        
        public LockFileResponse() {
        }
        
        public LockFileResponse(FileLocker.DevService.LockFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LockFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LockFileResult;
        
        public LockFileResponseBody() {
        }
        
        public LockFileResponseBody(string LockFileResult) {
            this.LockFileResult = LockFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnlockFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnlockFile", Namespace="http://tempuri.org/", Order=0)]
        public FileLocker.DevService.UnlockFileRequestBody Body;
        
        public UnlockFileRequest() {
        }
        
        public UnlockFileRequest(FileLocker.DevService.UnlockFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnlockFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        public UnlockFileRequestBody() {
        }
        
        public UnlockFileRequestBody(string filePath, string userName) {
            this.filePath = filePath;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnlockFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnlockFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileLocker.DevService.UnlockFileResponseBody Body;
        
        public UnlockFileResponse() {
        }
        
        public UnlockFileResponse(FileLocker.DevService.UnlockFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnlockFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UnlockFileResult;
        
        public UnlockFileResponseBody() {
        }
        
        public UnlockFileResponseBody(string UnlockFileResult) {
            this.UnlockFileResult = UnlockFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLockedFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLockedFile", Namespace="http://tempuri.org/", Order=0)]
        public FileLocker.DevService.GetLockedFileRequestBody Body;
        
        public GetLockedFileRequest() {
        }
        
        public GetLockedFileRequest(FileLocker.DevService.GetLockedFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLockedFileRequestBody {
        
        public GetLockedFileRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLockedFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLockedFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileLocker.DevService.GetLockedFileResponseBody Body;
        
        public GetLockedFileResponse() {
        }
        
        public GetLockedFileResponse(FileLocker.DevService.GetLockedFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLockedFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FileLocker.DevService.ArrayOfString[] GetLockedFileResult;
        
        public GetLockedFileResponseBody() {
        }
        
        public GetLockedFileResponseBody(FileLocker.DevService.ArrayOfString[] GetLockedFileResult) {
            this.GetLockedFileResult = GetLockedFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : FileLocker.DevService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<FileLocker.DevService.WebServiceSoap>, FileLocker.DevService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileLocker.DevService.LockFileResponse FileLocker.DevService.WebServiceSoap.LockFile(FileLocker.DevService.LockFileRequest request) {
            return base.Channel.LockFile(request);
        }
        
        public string LockFile(string filePath, string userName) {
            FileLocker.DevService.LockFileRequest inValue = new FileLocker.DevService.LockFileRequest();
            inValue.Body = new FileLocker.DevService.LockFileRequestBody();
            inValue.Body.filePath = filePath;
            inValue.Body.userName = userName;
            FileLocker.DevService.LockFileResponse retVal = ((FileLocker.DevService.WebServiceSoap)(this)).LockFile(inValue);
            return retVal.Body.LockFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileLocker.DevService.UnlockFileResponse FileLocker.DevService.WebServiceSoap.UnlockFile(FileLocker.DevService.UnlockFileRequest request) {
            return base.Channel.UnlockFile(request);
        }
        
        public string UnlockFile(string filePath, string userName) {
            FileLocker.DevService.UnlockFileRequest inValue = new FileLocker.DevService.UnlockFileRequest();
            inValue.Body = new FileLocker.DevService.UnlockFileRequestBody();
            inValue.Body.filePath = filePath;
            inValue.Body.userName = userName;
            FileLocker.DevService.UnlockFileResponse retVal = ((FileLocker.DevService.WebServiceSoap)(this)).UnlockFile(inValue);
            return retVal.Body.UnlockFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileLocker.DevService.GetLockedFileResponse FileLocker.DevService.WebServiceSoap.GetLockedFile(FileLocker.DevService.GetLockedFileRequest request) {
            return base.Channel.GetLockedFile(request);
        }
        
        public FileLocker.DevService.ArrayOfString[] GetLockedFile() {
            FileLocker.DevService.GetLockedFileRequest inValue = new FileLocker.DevService.GetLockedFileRequest();
            inValue.Body = new FileLocker.DevService.GetLockedFileRequestBody();
            FileLocker.DevService.GetLockedFileResponse retVal = ((FileLocker.DevService.WebServiceSoap)(this)).GetLockedFile(inValue);
            return retVal.Body.GetLockedFileResult;
        }
    }
}
