//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("MGModel", "FK_MG_comment_MG_photo", "MG_album", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MasonryGallery.MG_album), "MG_comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MasonryGallery.MG_comment), true)]
[assembly: EdmRelationshipAttribute("MGModel", "FK_MG_description_MG_photo", "MG_album", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MasonryGallery.MG_album), "MG_description", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MasonryGallery.MG_description), true)]
[assembly: EdmRelationshipAttribute("MGModel", "FK_MG_photo_MG_gallery", "MG_gallery", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MasonryGallery.MG_gallery), "MG_album", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MasonryGallery.MG_album), true)]
[assembly: EdmRelationshipAttribute("MGModel", "FK_MG_subpic_MG_album", "MG_album", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MasonryGallery.MG_album), "MG_subpic", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MasonryGallery.MG_subpic), true)]
[assembly: EdmRelationshipAttribute("MGModel", "FK_MG_langusing_MG_gallery", "MG_gallery", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MasonryGallery.MG_gallery), "MG_langusing", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MasonryGallery.MG_langusing), true)]
[assembly: EdmRelationshipAttribute("MGModel", "FK_MG_langusing_MG_lang", "MG_lang", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MasonryGallery.MG_lang), "MG_langusing", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MasonryGallery.MG_langusing), true)]

#endregion

namespace MasonryGallery
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class MGEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“MGEntities”部分中的连接字符串初始化新 MGEntities 对象。
        /// </summary>
        public MGEntities() : base("name=MGEntities", "MGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MGEntities 对象。
        /// </summary>
        public MGEntities(string connectionString) : base(connectionString, "MGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MGEntities 对象。
        /// </summary>
        public MGEntities(EntityConnection connection) : base(connection, "MGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MG_album> MG_album
        {
            get
            {
                if ((_MG_album == null))
                {
                    _MG_album = base.CreateObjectSet<MG_album>("MG_album");
                }
                return _MG_album;
            }
        }
        private ObjectSet<MG_album> _MG_album;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MG_comment> MG_comment
        {
            get
            {
                if ((_MG_comment == null))
                {
                    _MG_comment = base.CreateObjectSet<MG_comment>("MG_comment");
                }
                return _MG_comment;
            }
        }
        private ObjectSet<MG_comment> _MG_comment;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MG_description> MG_description
        {
            get
            {
                if ((_MG_description == null))
                {
                    _MG_description = base.CreateObjectSet<MG_description>("MG_description");
                }
                return _MG_description;
            }
        }
        private ObjectSet<MG_description> _MG_description;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MG_gallery> MG_gallery
        {
            get
            {
                if ((_MG_gallery == null))
                {
                    _MG_gallery = base.CreateObjectSet<MG_gallery>("MG_gallery");
                }
                return _MG_gallery;
            }
        }
        private ObjectSet<MG_gallery> _MG_gallery;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MG_lang> MG_lang
        {
            get
            {
                if ((_MG_lang == null))
                {
                    _MG_lang = base.CreateObjectSet<MG_lang>("MG_lang");
                }
                return _MG_lang;
            }
        }
        private ObjectSet<MG_lang> _MG_lang;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MG_langusing> MG_langusing
        {
            get
            {
                if ((_MG_langusing == null))
                {
                    _MG_langusing = base.CreateObjectSet<MG_langusing>("MG_langusing");
                }
                return _MG_langusing;
            }
        }
        private ObjectSet<MG_langusing> _MG_langusing;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MG_subpic> MG_subpic
        {
            get
            {
                if ((_MG_subpic == null))
                {
                    _MG_subpic = base.CreateObjectSet<MG_subpic>("MG_subpic");
                }
                return _MG_subpic;
            }
        }
        private ObjectSet<MG_subpic> _MG_subpic;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MG_theme> MG_theme
        {
            get
            {
                if ((_MG_theme == null))
                {
                    _MG_theme = base.CreateObjectSet<MG_theme>("MG_theme");
                }
                return _MG_theme;
            }
        }
        private ObjectSet<MG_theme> _MG_theme;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 MG_album EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMG_album(MG_album mG_album)
        {
            base.AddObject("MG_album", mG_album);
        }
    
        /// <summary>
        /// 用于向 MG_comment EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMG_comment(MG_comment mG_comment)
        {
            base.AddObject("MG_comment", mG_comment);
        }
    
        /// <summary>
        /// 用于向 MG_description EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMG_description(MG_description mG_description)
        {
            base.AddObject("MG_description", mG_description);
        }
    
        /// <summary>
        /// 用于向 MG_gallery EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMG_gallery(MG_gallery mG_gallery)
        {
            base.AddObject("MG_gallery", mG_gallery);
        }
    
        /// <summary>
        /// 用于向 MG_lang EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMG_lang(MG_lang mG_lang)
        {
            base.AddObject("MG_lang", mG_lang);
        }
    
        /// <summary>
        /// 用于向 MG_langusing EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMG_langusing(MG_langusing mG_langusing)
        {
            base.AddObject("MG_langusing", mG_langusing);
        }
    
        /// <summary>
        /// 用于向 MG_subpic EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMG_subpic(MG_subpic mG_subpic)
        {
            base.AddObject("MG_subpic", mG_subpic);
        }
    
        /// <summary>
        /// 用于向 MG_theme EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMG_theme(MG_theme mG_theme)
        {
            base.AddObject("MG_theme", mG_theme);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MGModel", Name="MG_album")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MG_album : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MG_album 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="sort">sort 属性的初始值。</param>
        /// <param name="showWidth">showWidth 属性的初始值。</param>
        /// <param name="thumbWidth">thumbWidth 属性的初始值。</param>
        /// <param name="gallery_id">gallery_id 属性的初始值。</param>
        /// <param name="mainpicurl">mainpicurl 属性的初始值。</param>
        /// <param name="mainpicWidth">mainpicWidth 属性的初始值。</param>
        /// <param name="mainpicHeight">mainpicHeight 属性的初始值。</param>
        /// <param name="subpicWidth">subpicWidth 属性的初始值。</param>
        /// <param name="yUPOO_photoId">YUPOO_photoId 属性的初始值。</param>
        /// <param name="mainpicurl_origin">mainpicurl_origin 属性的初始值。</param>
        public static MG_album CreateMG_album(global::System.Int32 id, global::System.Int32 sort, global::System.Int32 showWidth, global::System.Int32 thumbWidth, global::System.Int32 gallery_id, global::System.String mainpicurl, global::System.Int32 mainpicWidth, global::System.Int32 mainpicHeight, global::System.Int32 subpicWidth, global::System.String yUPOO_photoId, global::System.String mainpicurl_origin)
        {
            MG_album mG_album = new MG_album();
            mG_album.id = id;
            mG_album.sort = sort;
            mG_album.showWidth = showWidth;
            mG_album.thumbWidth = thumbWidth;
            mG_album.gallery_id = gallery_id;
            mG_album.mainpicurl = mainpicurl;
            mG_album.mainpicWidth = mainpicWidth;
            mG_album.mainpicHeight = mainpicHeight;
            mG_album.subpicWidth = subpicWidth;
            mG_album.YUPOO_photoId = yUPOO_photoId;
            mG_album.mainpicurl_origin = mainpicurl_origin;
            return mG_album;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sort
        {
            get
            {
                return _sort;
            }
            set
            {
                OnsortChanging(value);
                ReportPropertyChanging("sort");
                _sort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sort");
                OnsortChanged();
            }
        }
        private global::System.Int32 _sort;
        partial void OnsortChanging(global::System.Int32 value);
        partial void OnsortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 showWidth
        {
            get
            {
                return _showWidth;
            }
            set
            {
                OnshowWidthChanging(value);
                ReportPropertyChanging("showWidth");
                _showWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("showWidth");
                OnshowWidthChanged();
            }
        }
        private global::System.Int32 _showWidth;
        partial void OnshowWidthChanging(global::System.Int32 value);
        partial void OnshowWidthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 thumbWidth
        {
            get
            {
                return _thumbWidth;
            }
            set
            {
                OnthumbWidthChanging(value);
                ReportPropertyChanging("thumbWidth");
                _thumbWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("thumbWidth");
                OnthumbWidthChanged();
            }
        }
        private global::System.Int32 _thumbWidth;
        partial void OnthumbWidthChanging(global::System.Int32 value);
        partial void OnthumbWidthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gallery_id
        {
            get
            {
                return _gallery_id;
            }
            set
            {
                Ongallery_idChanging(value);
                ReportPropertyChanging("gallery_id");
                _gallery_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gallery_id");
                Ongallery_idChanged();
            }
        }
        private global::System.Int32 _gallery_id;
        partial void Ongallery_idChanging(global::System.Int32 value);
        partial void Ongallery_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mainpicurl
        {
            get
            {
                return _mainpicurl;
            }
            set
            {
                OnmainpicurlChanging(value);
                ReportPropertyChanging("mainpicurl");
                _mainpicurl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mainpicurl");
                OnmainpicurlChanged();
            }
        }
        private global::System.String _mainpicurl;
        partial void OnmainpicurlChanging(global::System.String value);
        partial void OnmainpicurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mainpicWidth
        {
            get
            {
                return _mainpicWidth;
            }
            set
            {
                OnmainpicWidthChanging(value);
                ReportPropertyChanging("mainpicWidth");
                _mainpicWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mainpicWidth");
                OnmainpicWidthChanged();
            }
        }
        private global::System.Int32 _mainpicWidth;
        partial void OnmainpicWidthChanging(global::System.Int32 value);
        partial void OnmainpicWidthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mainpicHeight
        {
            get
            {
                return _mainpicHeight;
            }
            set
            {
                OnmainpicHeightChanging(value);
                ReportPropertyChanging("mainpicHeight");
                _mainpicHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mainpicHeight");
                OnmainpicHeightChanged();
            }
        }
        private global::System.Int32 _mainpicHeight;
        partial void OnmainpicHeightChanging(global::System.Int32 value);
        partial void OnmainpicHeightChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 subpicWidth
        {
            get
            {
                return _subpicWidth;
            }
            set
            {
                OnsubpicWidthChanging(value);
                ReportPropertyChanging("subpicWidth");
                _subpicWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("subpicWidth");
                OnsubpicWidthChanged();
            }
        }
        private global::System.Int32 _subpicWidth;
        partial void OnsubpicWidthChanging(global::System.Int32 value);
        partial void OnsubpicWidthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String YUPOO_photoId
        {
            get
            {
                return _YUPOO_photoId;
            }
            set
            {
                OnYUPOO_photoIdChanging(value);
                ReportPropertyChanging("YUPOO_photoId");
                _YUPOO_photoId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("YUPOO_photoId");
                OnYUPOO_photoIdChanged();
            }
        }
        private global::System.String _YUPOO_photoId;
        partial void OnYUPOO_photoIdChanging(global::System.String value);
        partial void OnYUPOO_photoIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mainpicurl_origin
        {
            get
            {
                return _mainpicurl_origin;
            }
            set
            {
                Onmainpicurl_originChanging(value);
                ReportPropertyChanging("mainpicurl_origin");
                _mainpicurl_origin = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mainpicurl_origin");
                Onmainpicurl_originChanged();
            }
        }
        private global::System.String _mainpicurl_origin;
        partial void Onmainpicurl_originChanging(global::System.String value);
        partial void Onmainpicurl_originChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_comment_MG_photo", "MG_comment")]
        public EntityCollection<MG_comment> MG_comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MG_comment>("MGModel.FK_MG_comment_MG_photo", "MG_comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MG_comment>("MGModel.FK_MG_comment_MG_photo", "MG_comment", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_description_MG_photo", "MG_description")]
        public EntityCollection<MG_description> MG_description
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MG_description>("MGModel.FK_MG_description_MG_photo", "MG_description");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MG_description>("MGModel.FK_MG_description_MG_photo", "MG_description", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_photo_MG_gallery", "MG_gallery")]
        public MG_gallery MG_gallery
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_gallery>("MGModel.FK_MG_photo_MG_gallery", "MG_gallery").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_gallery>("MGModel.FK_MG_photo_MG_gallery", "MG_gallery").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MG_gallery> MG_galleryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_gallery>("MGModel.FK_MG_photo_MG_gallery", "MG_gallery");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MG_gallery>("MGModel.FK_MG_photo_MG_gallery", "MG_gallery", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_subpic_MG_album", "MG_subpic")]
        public EntityCollection<MG_subpic> MG_subpic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MG_subpic>("MGModel.FK_MG_subpic_MG_album", "MG_subpic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MG_subpic>("MGModel.FK_MG_subpic_MG_album", "MG_subpic", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MGModel", Name="MG_comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MG_comment : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MG_comment 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="content">content 属性的初始值。</param>
        /// <param name="time">time 属性的初始值。</param>
        /// <param name="name">name 属性的初始值。</param>
        /// <param name="avatar">avatar 属性的初始值。</param>
        /// <param name="album_id">album_id 属性的初始值。</param>
        public static MG_comment CreateMG_comment(global::System.Int32 id, global::System.String content, global::System.DateTime time, global::System.String name, global::System.String avatar, global::System.Int32 album_id)
        {
            MG_comment mG_comment = new MG_comment();
            mG_comment.id = id;
            mG_comment.content = content;
            mG_comment.time = time;
            mG_comment.name = name;
            mG_comment.avatar = avatar;
            mG_comment.album_id = album_id;
            return mG_comment;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private global::System.DateTime _time;
        partial void OntimeChanging(global::System.DateTime value);
        partial void OntimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String avatar
        {
            get
            {
                return _avatar;
            }
            set
            {
                OnavatarChanging(value);
                ReportPropertyChanging("avatar");
                _avatar = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("avatar");
                OnavatarChanged();
            }
        }
        private global::System.String _avatar;
        partial void OnavatarChanging(global::System.String value);
        partial void OnavatarChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 album_id
        {
            get
            {
                return _album_id;
            }
            set
            {
                Onalbum_idChanging(value);
                ReportPropertyChanging("album_id");
                _album_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("album_id");
                Onalbum_idChanged();
            }
        }
        private global::System.Int32 _album_id;
        partial void Onalbum_idChanging(global::System.Int32 value);
        partial void Onalbum_idChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_comment_MG_photo", "MG_album")]
        public MG_album MG_album
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_album>("MGModel.FK_MG_comment_MG_photo", "MG_album").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_album>("MGModel.FK_MG_comment_MG_photo", "MG_album").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MG_album> MG_albumReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_album>("MGModel.FK_MG_comment_MG_photo", "MG_album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MG_album>("MGModel.FK_MG_comment_MG_photo", "MG_album", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MGModel", Name="MG_description")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MG_description : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MG_description 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="lang_code">lang_code 属性的初始值。</param>
        /// <param name="album_id">album_id 属性的初始值。</param>
        /// <param name="title">title 属性的初始值。</param>
        /// <param name="content">content 属性的初始值。</param>
        public static MG_description CreateMG_description(global::System.Int32 id, global::System.String lang_code, global::System.Int32 album_id, global::System.String title, global::System.String content)
        {
            MG_description mG_description = new MG_description();
            mG_description.id = id;
            mG_description.lang_code = lang_code;
            mG_description.album_id = album_id;
            mG_description.title = title;
            mG_description.content = content;
            return mG_description;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lang_code
        {
            get
            {
                return _lang_code;
            }
            set
            {
                Onlang_codeChanging(value);
                ReportPropertyChanging("lang_code");
                _lang_code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lang_code");
                Onlang_codeChanged();
            }
        }
        private global::System.String _lang_code;
        partial void Onlang_codeChanging(global::System.String value);
        partial void Onlang_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 album_id
        {
            get
            {
                return _album_id;
            }
            set
            {
                Onalbum_idChanging(value);
                ReportPropertyChanging("album_id");
                _album_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("album_id");
                Onalbum_idChanged();
            }
        }
        private global::System.Int32 _album_id;
        partial void Onalbum_idChanging(global::System.Int32 value);
        partial void Onalbum_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_description_MG_photo", "MG_album")]
        public MG_album MG_album
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_album>("MGModel.FK_MG_description_MG_photo", "MG_album").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_album>("MGModel.FK_MG_description_MG_photo", "MG_album").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MG_album> MG_albumReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_album>("MGModel.FK_MG_description_MG_photo", "MG_album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MG_album>("MGModel.FK_MG_description_MG_photo", "MG_album", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MGModel", Name="MG_gallery")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MG_gallery : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MG_gallery 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="username">username 属性的初始值。</param>
        /// <param name="password">password 属性的初始值。</param>
        /// <param name="domainname">domainname 属性的初始值。</param>
        /// <param name="default_lang_code">default_lang_code 属性的初始值。</param>
        /// <param name="width">width 属性的初始值。</param>
        /// <param name="border">border 属性的初始值。</param>
        /// <param name="margin">margin 属性的初始值。</param>
        /// <param name="color1">color1 属性的初始值。</param>
        /// <param name="color2">color2 属性的初始值。</param>
        /// <param name="color3">color3 属性的初始值。</param>
        /// <param name="type">type 属性的初始值。</param>
        /// <param name="yUPOO_albumId">YUPOO_albumId 属性的初始值。</param>
        /// <param name="opacity">opacity 属性的初始值。</param>
        public static MG_gallery CreateMG_gallery(global::System.Int32 id, global::System.String username, global::System.String password, global::System.String domainname, global::System.String default_lang_code, global::System.Int32 width, global::System.Int32 border, global::System.Int32 margin, global::System.String color1, global::System.String color2, global::System.String color3, global::System.String type, global::System.String yUPOO_albumId, global::System.Double opacity)
        {
            MG_gallery mG_gallery = new MG_gallery();
            mG_gallery.id = id;
            mG_gallery.username = username;
            mG_gallery.password = password;
            mG_gallery.domainname = domainname;
            mG_gallery.default_lang_code = default_lang_code;
            mG_gallery.width = width;
            mG_gallery.border = border;
            mG_gallery.margin = margin;
            mG_gallery.color1 = color1;
            mG_gallery.color2 = color2;
            mG_gallery.color3 = color3;
            mG_gallery.type = type;
            mG_gallery.YUPOO_albumId = yUPOO_albumId;
            mG_gallery.opacity = opacity;
            return mG_gallery;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String domainname
        {
            get
            {
                return _domainname;
            }
            set
            {
                OndomainnameChanging(value);
                ReportPropertyChanging("domainname");
                _domainname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("domainname");
                OndomainnameChanged();
            }
        }
        private global::System.String _domainname;
        partial void OndomainnameChanging(global::System.String value);
        partial void OndomainnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String default_lang_code
        {
            get
            {
                return _default_lang_code;
            }
            set
            {
                Ondefault_lang_codeChanging(value);
                ReportPropertyChanging("default_lang_code");
                _default_lang_code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("default_lang_code");
                Ondefault_lang_codeChanged();
            }
        }
        private global::System.String _default_lang_code;
        partial void Ondefault_lang_codeChanging(global::System.String value);
        partial void Ondefault_lang_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 width
        {
            get
            {
                return _width;
            }
            set
            {
                OnwidthChanging(value);
                ReportPropertyChanging("width");
                _width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("width");
                OnwidthChanged();
            }
        }
        private global::System.Int32 _width;
        partial void OnwidthChanging(global::System.Int32 value);
        partial void OnwidthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 border
        {
            get
            {
                return _border;
            }
            set
            {
                OnborderChanging(value);
                ReportPropertyChanging("border");
                _border = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("border");
                OnborderChanged();
            }
        }
        private global::System.Int32 _border;
        partial void OnborderChanging(global::System.Int32 value);
        partial void OnborderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 margin
        {
            get
            {
                return _margin;
            }
            set
            {
                OnmarginChanging(value);
                ReportPropertyChanging("margin");
                _margin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("margin");
                OnmarginChanged();
            }
        }
        private global::System.Int32 _margin;
        partial void OnmarginChanging(global::System.Int32 value);
        partial void OnmarginChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bodyWidth
        {
            get
            {
                return _bodyWidth;
            }
            set
            {
                OnbodyWidthChanging(value);
                ReportPropertyChanging("bodyWidth");
                _bodyWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bodyWidth");
                OnbodyWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _bodyWidth;
        partial void OnbodyWidthChanging(Nullable<global::System.Int32> value);
        partial void OnbodyWidthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String color1
        {
            get
            {
                return _color1;
            }
            set
            {
                Oncolor1Changing(value);
                ReportPropertyChanging("color1");
                _color1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("color1");
                Oncolor1Changed();
            }
        }
        private global::System.String _color1;
        partial void Oncolor1Changing(global::System.String value);
        partial void Oncolor1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String color2
        {
            get
            {
                return _color2;
            }
            set
            {
                Oncolor2Changing(value);
                ReportPropertyChanging("color2");
                _color2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("color2");
                Oncolor2Changed();
            }
        }
        private global::System.String _color2;
        partial void Oncolor2Changing(global::System.String value);
        partial void Oncolor2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String color3
        {
            get
            {
                return _color3;
            }
            set
            {
                Oncolor3Changing(value);
                ReportPropertyChanging("color3");
                _color3 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("color3");
                Oncolor3Changed();
            }
        }
        private global::System.String _color3;
        partial void Oncolor3Changing(global::System.String value);
        partial void Oncolor3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String YUPOO_albumId
        {
            get
            {
                return _YUPOO_albumId;
            }
            set
            {
                OnYUPOO_albumIdChanging(value);
                ReportPropertyChanging("YUPOO_albumId");
                _YUPOO_albumId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("YUPOO_albumId");
                OnYUPOO_albumIdChanged();
            }
        }
        private global::System.String _YUPOO_albumId;
        partial void OnYUPOO_albumIdChanging(global::System.String value);
        partial void OnYUPOO_albumIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double opacity
        {
            get
            {
                return _opacity;
            }
            set
            {
                OnopacityChanging(value);
                ReportPropertyChanging("opacity");
                _opacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("opacity");
                OnopacityChanged();
            }
        }
        private global::System.Double _opacity;
        partial void OnopacityChanging(global::System.Double value);
        partial void OnopacityChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_photo_MG_gallery", "MG_album")]
        public EntityCollection<MG_album> MG_album
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MG_album>("MGModel.FK_MG_photo_MG_gallery", "MG_album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MG_album>("MGModel.FK_MG_photo_MG_gallery", "MG_album", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_langusing_MG_gallery", "MG_langusing")]
        public EntityCollection<MG_langusing> MG_langusing
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MG_langusing>("MGModel.FK_MG_langusing_MG_gallery", "MG_langusing");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MG_langusing>("MGModel.FK_MG_langusing_MG_gallery", "MG_langusing", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MGModel", Name="MG_lang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MG_lang : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MG_lang 对象。
        /// </summary>
        /// <param name="string">string 属性的初始值。</param>
        /// <param name="code">code 属性的初始值。</param>
        public static MG_lang CreateMG_lang(global::System.String @string, global::System.String code)
        {
            MG_lang mG_lang = new MG_lang();
            mG_lang.@string = @string;
            mG_lang.code = code;
            return mG_lang;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String @string
        {
            get
            {
                return _string;
            }
            set
            {
                OnstringChanging(value);
                ReportPropertyChanging("string");
                _string = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("string");
                OnstringChanged();
            }
        }
        private global::System.String _string;
        partial void OnstringChanging(global::System.String value);
        partial void OnstringChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String code
        {
            get
            {
                return _code;
            }
            set
            {
                if (_code != value)
                {
                    OncodeChanging(value);
                    ReportPropertyChanging("code");
                    _code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("code");
                    OncodeChanged();
                }
            }
        }
        private global::System.String _code;
        partial void OncodeChanging(global::System.String value);
        partial void OncodeChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_langusing_MG_lang", "MG_langusing")]
        public EntityCollection<MG_langusing> MG_langusing
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MG_langusing>("MGModel.FK_MG_langusing_MG_lang", "MG_langusing");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MG_langusing>("MGModel.FK_MG_langusing_MG_lang", "MG_langusing", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MGModel", Name="MG_langusing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MG_langusing : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MG_langusing 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="gallery_id">gallery_id 属性的初始值。</param>
        /// <param name="lang_code">lang_code 属性的初始值。</param>
        /// <param name="titile">titile 属性的初始值。</param>
        public static MG_langusing CreateMG_langusing(global::System.Int32 id, global::System.Int32 gallery_id, global::System.String lang_code, global::System.String titile)
        {
            MG_langusing mG_langusing = new MG_langusing();
            mG_langusing.id = id;
            mG_langusing.gallery_id = gallery_id;
            mG_langusing.lang_code = lang_code;
            mG_langusing.titile = titile;
            return mG_langusing;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gallery_id
        {
            get
            {
                return _gallery_id;
            }
            set
            {
                Ongallery_idChanging(value);
                ReportPropertyChanging("gallery_id");
                _gallery_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gallery_id");
                Ongallery_idChanged();
            }
        }
        private global::System.Int32 _gallery_id;
        partial void Ongallery_idChanging(global::System.Int32 value);
        partial void Ongallery_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lang_code
        {
            get
            {
                return _lang_code;
            }
            set
            {
                Onlang_codeChanging(value);
                ReportPropertyChanging("lang_code");
                _lang_code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lang_code");
                Onlang_codeChanged();
            }
        }
        private global::System.String _lang_code;
        partial void Onlang_codeChanging(global::System.String value);
        partial void Onlang_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titile
        {
            get
            {
                return _titile;
            }
            set
            {
                OntitileChanging(value);
                ReportPropertyChanging("titile");
                _titile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titile");
                OntitileChanged();
            }
        }
        private global::System.String _titile;
        partial void OntitileChanging(global::System.String value);
        partial void OntitileChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_langusing_MG_gallery", "MG_gallery")]
        public MG_gallery MG_gallery
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_gallery>("MGModel.FK_MG_langusing_MG_gallery", "MG_gallery").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_gallery>("MGModel.FK_MG_langusing_MG_gallery", "MG_gallery").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MG_gallery> MG_galleryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_gallery>("MGModel.FK_MG_langusing_MG_gallery", "MG_gallery");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MG_gallery>("MGModel.FK_MG_langusing_MG_gallery", "MG_gallery", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_langusing_MG_lang", "MG_lang")]
        public MG_lang MG_lang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_lang>("MGModel.FK_MG_langusing_MG_lang", "MG_lang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_lang>("MGModel.FK_MG_langusing_MG_lang", "MG_lang").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MG_lang> MG_langReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_lang>("MGModel.FK_MG_langusing_MG_lang", "MG_lang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MG_lang>("MGModel.FK_MG_langusing_MG_lang", "MG_lang", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MGModel", Name="MG_subpic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MG_subpic : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MG_subpic 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="url">url 属性的初始值。</param>
        /// <param name="album_id">album_id 属性的初始值。</param>
        /// <param name="sort">sort 属性的初始值。</param>
        /// <param name="width">width 属性的初始值。</param>
        /// <param name="height">height 属性的初始值。</param>
        /// <param name="yUPOO_photoId">YUPOO_photoId 属性的初始值。</param>
        /// <param name="url_origin">url_origin 属性的初始值。</param>
        public static MG_subpic CreateMG_subpic(global::System.Int32 id, global::System.String url, global::System.Int32 album_id, global::System.Int32 sort, global::System.Int32 width, global::System.Int32 height, global::System.String yUPOO_photoId, global::System.String url_origin)
        {
            MG_subpic mG_subpic = new MG_subpic();
            mG_subpic.id = id;
            mG_subpic.url = url;
            mG_subpic.album_id = album_id;
            mG_subpic.sort = sort;
            mG_subpic.width = width;
            mG_subpic.height = height;
            mG_subpic.YUPOO_photoId = yUPOO_photoId;
            mG_subpic.url_origin = url_origin;
            return mG_subpic;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 album_id
        {
            get
            {
                return _album_id;
            }
            set
            {
                Onalbum_idChanging(value);
                ReportPropertyChanging("album_id");
                _album_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("album_id");
                Onalbum_idChanged();
            }
        }
        private global::System.Int32 _album_id;
        partial void Onalbum_idChanging(global::System.Int32 value);
        partial void Onalbum_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sort
        {
            get
            {
                return _sort;
            }
            set
            {
                OnsortChanging(value);
                ReportPropertyChanging("sort");
                _sort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sort");
                OnsortChanged();
            }
        }
        private global::System.Int32 _sort;
        partial void OnsortChanging(global::System.Int32 value);
        partial void OnsortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 width
        {
            get
            {
                return _width;
            }
            set
            {
                OnwidthChanging(value);
                ReportPropertyChanging("width");
                _width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("width");
                OnwidthChanged();
            }
        }
        private global::System.Int32 _width;
        partial void OnwidthChanging(global::System.Int32 value);
        partial void OnwidthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 height
        {
            get
            {
                return _height;
            }
            set
            {
                OnheightChanging(value);
                ReportPropertyChanging("height");
                _height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("height");
                OnheightChanged();
            }
        }
        private global::System.Int32 _height;
        partial void OnheightChanging(global::System.Int32 value);
        partial void OnheightChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String YUPOO_photoId
        {
            get
            {
                return _YUPOO_photoId;
            }
            set
            {
                OnYUPOO_photoIdChanging(value);
                ReportPropertyChanging("YUPOO_photoId");
                _YUPOO_photoId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("YUPOO_photoId");
                OnYUPOO_photoIdChanged();
            }
        }
        private global::System.String _YUPOO_photoId;
        partial void OnYUPOO_photoIdChanging(global::System.String value);
        partial void OnYUPOO_photoIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url_origin
        {
            get
            {
                return _url_origin;
            }
            set
            {
                Onurl_originChanging(value);
                ReportPropertyChanging("url_origin");
                _url_origin = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url_origin");
                Onurl_originChanged();
            }
        }
        private global::System.String _url_origin;
        partial void Onurl_originChanging(global::System.String value);
        partial void Onurl_originChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MGModel", "FK_MG_subpic_MG_album", "MG_album")]
        public MG_album MG_album
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_album>("MGModel.FK_MG_subpic_MG_album", "MG_album").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_album>("MGModel.FK_MG_subpic_MG_album", "MG_album").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MG_album> MG_albumReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MG_album>("MGModel.FK_MG_subpic_MG_album", "MG_album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MG_album>("MGModel.FK_MG_subpic_MG_album", "MG_album", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MGModel", Name="MG_theme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MG_theme : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MG_theme 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="color1">color1 属性的初始值。</param>
        /// <param name="color2">color2 属性的初始值。</param>
        /// <param name="color3">color3 属性的初始值。</param>
        /// <param name="sort">sort 属性的初始值。</param>
        public static MG_theme CreateMG_theme(global::System.Int32 id, global::System.String color1, global::System.String color2, global::System.String color3, global::System.Int32 sort)
        {
            MG_theme mG_theme = new MG_theme();
            mG_theme.id = id;
            mG_theme.color1 = color1;
            mG_theme.color2 = color2;
            mG_theme.color3 = color3;
            mG_theme.sort = sort;
            return mG_theme;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String color1
        {
            get
            {
                return _color1;
            }
            set
            {
                Oncolor1Changing(value);
                ReportPropertyChanging("color1");
                _color1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("color1");
                Oncolor1Changed();
            }
        }
        private global::System.String _color1;
        partial void Oncolor1Changing(global::System.String value);
        partial void Oncolor1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String color2
        {
            get
            {
                return _color2;
            }
            set
            {
                Oncolor2Changing(value);
                ReportPropertyChanging("color2");
                _color2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("color2");
                Oncolor2Changed();
            }
        }
        private global::System.String _color2;
        partial void Oncolor2Changing(global::System.String value);
        partial void Oncolor2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String color3
        {
            get
            {
                return _color3;
            }
            set
            {
                Oncolor3Changing(value);
                ReportPropertyChanging("color3");
                _color3 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("color3");
                Oncolor3Changed();
            }
        }
        private global::System.String _color3;
        partial void Oncolor3Changing(global::System.String value);
        partial void Oncolor3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sort
        {
            get
            {
                return _sort;
            }
            set
            {
                OnsortChanging(value);
                ReportPropertyChanging("sort");
                _sort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sort");
                OnsortChanged();
            }
        }
        private global::System.Int32 _sort;
        partial void OnsortChanging(global::System.Int32 value);
        partial void OnsortChanged();

        #endregion
    
    }

    #endregion
    
}
