//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.237
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCDocService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServicesSoap")]
    public interface WebServicesSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetDocResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDoc", ReplyAction="*")]
        GCDocService.ServiceReference1.GetDocResponse GetDoc(GCDocService.ServiceReference1.GetDocRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 filename 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDoc", ReplyAction="*")]
        GCDocService.ServiceReference1.DelDocResponse DelDoc(GCDocService.ServiceReference1.DelDocRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDoc", Namespace="http://tempuri.org/", Order=0)]
        public GCDocService.ServiceReference1.GetDocRequestBody Body;
        
        public GetDocRequest() {
        }
        
        public GetDocRequest(GCDocService.ServiceReference1.GetDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDocRequestBody {
        
        public GetDocRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public GCDocService.ServiceReference1.GetDocResponseBody Body;
        
        public GetDocResponse() {
        }
        
        public GetDocResponse(GCDocService.ServiceReference1.GetDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDocResult;
        
        public GetDocResponseBody() {
        }
        
        public GetDocResponseBody(string GetDocResult) {
            this.GetDocResult = GetDocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDoc", Namespace="http://tempuri.org/", Order=0)]
        public GCDocService.ServiceReference1.DelDocRequestBody Body;
        
        public DelDocRequest() {
        }
        
        public DelDocRequest(GCDocService.ServiceReference1.DelDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelDocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public DelDocRequestBody() {
        }
        
        public DelDocRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public GCDocService.ServiceReference1.DelDocResponseBody Body;
        
        public DelDocResponse() {
        }
        
        public DelDocResponse(GCDocService.ServiceReference1.DelDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DelDocResponseBody {
        
        public DelDocResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicesSoapChannel : GCDocService.ServiceReference1.WebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicesSoapClient : System.ServiceModel.ClientBase<GCDocService.ServiceReference1.WebServicesSoap>, GCDocService.ServiceReference1.WebServicesSoap {
        
        public WebServicesSoapClient() {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GCDocService.ServiceReference1.GetDocResponse GCDocService.ServiceReference1.WebServicesSoap.GetDoc(GCDocService.ServiceReference1.GetDocRequest request) {
            return base.Channel.GetDoc(request);
        }
        
        public string GetDoc() {
            GCDocService.ServiceReference1.GetDocRequest inValue = new GCDocService.ServiceReference1.GetDocRequest();
            inValue.Body = new GCDocService.ServiceReference1.GetDocRequestBody();
            GCDocService.ServiceReference1.GetDocResponse retVal = ((GCDocService.ServiceReference1.WebServicesSoap)(this)).GetDoc(inValue);
            return retVal.Body.GetDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GCDocService.ServiceReference1.DelDocResponse GCDocService.ServiceReference1.WebServicesSoap.DelDoc(GCDocService.ServiceReference1.DelDocRequest request) {
            return base.Channel.DelDoc(request);
        }
        
        public void DelDoc(string filename) {
            GCDocService.ServiceReference1.DelDocRequest inValue = new GCDocService.ServiceReference1.DelDocRequest();
            inValue.Body = new GCDocService.ServiceReference1.DelDocRequestBody();
            inValue.Body.filename = filename;
            GCDocService.ServiceReference1.DelDocResponse retVal = ((GCDocService.ServiceReference1.WebServicesSoap)(this)).DelDoc(inValue);
        }
    }
}
